### ISSUE TITLE
Port to Godot3

### ISSUE THREAD

**Issue by Luraktinus** [HassanHeydariNasab/turo#1]
porting to godot3 gives me the ability to contribute without downloading the obsolete version from an archive

**Comment by HassanHeydariNasab** [comment]
Godot 3 has several problems with Android. I'm waiting for Godot 3.1

**Comment by Luraktinus** [comment]
ok

**Comment by HassanHeydariNasab** [comment]
https://github.com/HassanHeydariNasab/turo3
