### ISSUE TITLE
Translate repository in English to welcome contributors

### ISSUE THREAD

**Issue by gkaklas** [HassanHeydariNasab/turo#4]
I was just curious about the source code, unfortunately I can't even understand the file names, or the commit messages (I don't think I'm the only one). 🙁

Open Source projects are usually in English regardless of country so anyone can help in development, patch vulnerabilities, fix bugs etc and help make the project better. 🙂

**Comment by HassanHeydariNasab** [comment]
https://github.com/HassanHeydariNasab/turo3/commit/7ef4a779362c4beee3cfdaad6ab79e4480e2ca5c
